- menu_name: "Services"

- name: "Contact"
  url: "/contact/"
  title: "Contact"

- name: "RSS"
  url: "http://feeds.sydiproject.com/Sydi"
  title: "Subscribe to RSS Feed"

- name: "Email"
  url: "/email/"
  title: "Subscribe to newsletter"
